# Generated by Django 3.2 on 2021-05-29 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qr_survey', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Posters',
            new_name='Poster',
        ),
    ]
